# This is a template for the Streamlit secrets file
# Create a file named ".streamlit/secrets.toml" with your actual secrets
# Do NOT commit the actual secrets.toml file to GitHub

# OpenAI API credentials
OPENAI_API_KEY = "your-openai-api-key"

# Supabase credentials
SUPABASE_URL = "your-supabase-url"
SUPABASE_KEY = "your-supabase-key"
SUPABASE_DB_PASSWORD = "your-supabase-db-password"

# Application settings
APP_NAME = "AI Teaching Assistant"
DEBUG = "False"
